### ISSUE TITLE
key.example.txt syntax help

### ISSUE THREAD

**Issue by ssaffare** [canontech/staking-payouts#67]
I'm looking to get more clarity on how to read/use a "key.txt" file. The file contains the line 
`bottom drive obey lake curtain smoke basket hold race lonely fit walk//Alice`
This is a 12 word mnemonic. 
1 can I use a hex private key instead? 
2 what does "//Alice" denote?
3 if there are multiple accounts being used, how do you make a proper array?
4 are there differences for a Kusama and Polkadot key?

As a slight aside, the syntax for multiple stash accounts in the "stashes.example.json" file is 
[
  "kldfjfaklsdklsdf"
  "sdfjklakldsjdfkl"
]
OR
[
  "jdkasfdjklss", "kdffadjkljsd"
]

Thank you kindly for this help.

**Comment by emostov** [comment]
1) I haven't tested, but it should not be an issue
2) This is an example of a hard derive, if you don't know what it is you probably can ignore it. Here is a section with some more info: https://substrate.dev/docs/en/knowledgebase/integrate/subkey#hd-key-derivation . The exact key I use here is the canonical "Alice" for substrate development.
3) You can only make payouts from one account. This account should have just enough to cover transaction fees.
4) Nope, same syntax.

> As a slight aside, the syntax for multiple stash accounts in the "stashes.example.json" file is

The latter with a `,`. So [ "jdkasfdjklss", "kdffadjkljsd" ] should work fine. (It expects a JSON array.)

Closing for now, but please reopen if you have any follow up questions and fee free to open another issue for different questions or feedback :)

**Comment by ssaffare** [comment]
Thank you thank you kindly for your quick response and help! And I apologize for my slow reply.

For all the payment questions I was confusing myself, yes, all payments should only be coming from 1 account (controller Accout) and therefore an array wouldn't be necessary. My mistake. Thank you again and for the use of your code!
