### ISSUE TITLE
Define update priorities

### ISSUE THREAD

**Issue by asymmetric** [canontech/staking-payouts#73]
What is the meaning of the "Low/Medium/High" priorities used for releases?

I think it would be useful to formally define it, so that people could then act accordingly.

**Comment by emostov** [comment]
Yeah I agree. My process for this repo is not exactly a science: essentially I look at the pokadot-js/api CHANGELOG to see if there is any new type updates that might break the api's ability to decode the metadata. 

If I am pretty sure the api will break decoding the metadata then I label the release High priority. 

If it I think it probably won't break anything but there still looks to be some type updates I label it "Medium" kind of as "probably ok, but better safe than sorry". 

If I put "Low" it means I didn't see any change that think will break things.

TBH I am not really on top of the type updates these days and its pretty easy to let something slip through so in an ideal world I would release regularly and users would update defensively. Its overkill but less risky.

**Comment by emostov** [comment]
Closing for now. Barring major breaking changes to the substrate metadata format, most updates should default too low priority since we don't need to update type defs anymore.
