### ISSUE TITLE
Support of centrifuge chain

### ISSUE THREAD

**Issue by novy4** [canontech/staking-payouts#74]
I am trying to use this app to collect rewards from centrifuge chain validator.
I am getting the log like:
` API/INIT: RPC methods not decorated: anchor_getAnchorById
METADATA: Unknown types found, no types for ProposalVotes`

rpc service is: wss://fullnode.centrifuge.io

is it possible to fix this somehow?

**Comment by emostov** [comment]
I can probably fix that exact issue, but I am not sure if this is the right tool; does the Centrifuge runtime use the staking pallet? If not this CLI will not be helpful

Checking here I don't see the staking pallet: https://github.com/centrifuge/centrifuge-chain/blob/parachain/runtime/centrifuge/src/lib.rs

**Comment by emostov** [comment]
Stale - feel free to reopen though.
